name = "demo-worker"
main = "workers/index.js"
compatibility_date = "2024-06-01" # 根据你实际wrangler版本日期

[site]
bucket = "./frontend"
entry-point = "workers" # 可选，如workers独立放workers目录

[build]
command = "" # 因为静态，无需build命令

[[routes]]
pattern = "demo-login-*.pages.dev/api/*"
script = "demo-worker"
